stages:
  - setup
  - test
  - build
  - deploy

# Step 1: Setup Environment & Install Dependencies
setup:
  stage: setup
  image: python:3.9
  before_script:
    - apt-get update && apt-get install -y git-lfs
    - git lfs install
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
    expire_in: 1 day

# Step 2: Run Tests (if applicable)
test:
  stage: test
  image: python:3.9
  script:
    - pytest tests/ --disable-warnings
  only:
    - main

# Step 3: Build Docker Image
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

# Step 4: Deploy to Server (Optional)
deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh
  script:
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "docker pull $CI_REGISTRY_IMAGE:latest && docker run -d -p 5000:5000 $CI_REGISTRY_IMAGE:latest"
  only:
    - main